import = [
    "~/.config/alacritty/kanagawa_wave.toml"
]

[window]
dynamic_padding = false
padding = { x = 20, y = 20 }
opacity = 0.85
title = "Terminal"

[scrolling]
multiplier = 20

[font]
normal = { family = "Maple Mono NF" }
# bold = { family = "Hack Nerd Font", style="Heavy" }
# italic = { family = "Hack Nerd Font", style="Semibold Italic" }
bold_italic = { family = "Maple Mono NF", style="Bold Italic" }
size = 10

[selection]
save_to_clipboard = true

# For mapping Shift + Enter to Neovim
[[keyboard.bindings]]
chars = "\u001b[13;2u"
key = "Return"
mods = "Shift"
