[window]
padding = { x = 20, y = 20 }
opacity = 0.66
title = "Terminal"

[scrolling]
multiplier = 25

[font]
normal = { family = "MartianMono Nerd Font", style= "Regular" }
size = 11

[selection]
save_to_clipboard = true
