format = """$character"""
right_format = """$battery $all """
add_newline = true

[jobs]
disabled = true

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[directory]
format = '[](white)[󰉋 $path$read_only]($style)[](white)'
style = 'bg:white black'
read_only = ' '

[c]
format = ' '

[python]
format = ' '

[lua]
format = ' '
# format = ' [](white)[ $version](bold blue bg:white)[](white)'

[bun]
# format = ' 󱌙'
disabled = true

[nodejs]
format = ' '

[package]
disabled = true

[battery]
charging_symbol = '[](green)[󰂄$percentage](white bg:green)[](green)'
discharging_symbol = '[](red)[󱊡$percentage](white bg:red)[](red)'
format = '$symbol'

[[battery.display]]
threshold = 25

[cmd_duration]
disabled = true

[git_branch]
format = ' [](blue)[󰘬 $branch](bold white bg:blue)[](blue)'

[git_status]
format = '$conflicted$stashed$deleted$renamed$modified$typechanged$staged$untracked'
up_to_date = ''
untracked = '[  $count](yellow)'
modified = '[ 󰤌 $count](fg:#ffaa00)'
staged = '[ 󰬳 $count](green)'
renamed = '[ 󰬲 $count](purple)'
deleted = ' [ $count](red)'
