add_newline = true
format = """$character"""
right_format = """$all"""

[line_break]
disabled = false


[username]
disabled = true

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[directory]
format = '[](white)[󰉋 $path$read_only]($style)[](white)'
style = 'bg:white black'

[lua]
format = ' [](white)[](bold black bg:white)[](white)'
# format = ' [](white)[ $version](bold blue bg:white)[](white)'


[cmd_duration]
disabled = true

[git_branch]
format = ' [](blue)[󰘬 $branch](bold white bg:blue)[](blue)'

[git_status]
format = '$conflicted$stashed$deleted$renamed$modified$typechanged$staged$untracked'

up_to_date = ''
untracked = '[  $count](yellow)'
modified = '[ 󰤌 $count](fg:#ffaa00)'
staged = '[ 󰬳 $count](green)'
renamed = '[ 󰬲 $count](purple)'
deleted = ' [ $count](red)'
